name: Build Typst.Net package
inputs:
  dotnet-version:
    description: .NET SDK version to install
    default: 10.x
  rust-version:
    description: Rust toolchain version to install
    default: 1.91.1
  package-version:
    description: Optional package version override
    required: false
  output-directory:
    description: Output directory for packed artifacts
    default: artifacts
runs:
  using: composite
  steps:
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Install build prerequisites
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          build-essential \
          pkg-config \
          libssl-dev \
          llvm \
          clang \
          zlib1g-dev \
          mingw-w64 \
          ca-certificates
        sudo rm -rf /var/lib/apt/lists/*

    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ inputs.rust-version }}
        profile: minimal

    - name: Ensure cargo in PATH
      shell: bash
      run: echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"

    - name: Add Rust cross-compilation targets
      shell: bash
      run: rustup target add x86_64-pc-windows-gnu x86_64-unknown-linux-gnu

    - name: Restore .NET solution
      shell: bash
      run: dotnet restore Typst.Net.sln

    - name: Pack Typst.Net
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p "${{ inputs.output-directory }}"
        version_arg=""
        if [ -n "${{ inputs.package-version }}" ]; then
          version_arg="/p:Version=${{ inputs.package-version }}"
        fi
        dotnet pack src/Typst.Net/Typst.Net.csproj -c Release -o "${{ inputs.output-directory }}" $version_arg
